config/routes.rb
Rails.application.routes.draw do
  resources :planetas
  resources :usuarios
  resources :noticias
  get 'home/index'
  root 'home#index'
# get 'signup', to: 'usuarios#new', as: 'signup'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/noticia.rb
class Noticia < ApplicationRecord
end

app/models/planeta.rb
class Planeta < ApplicationRecord
  def self.masa_de_la_tierra
    5.972e+24
  end
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/noticias_controller.rb
class NoticiasController < ApplicationController
  before_action :set_noticia, only: [:show, :edit, :update, :destroy]

  # GET /noticias
  # GET /noticias.json
  def index
    @noticias = Noticia.all
  end

  # GET /noticias/1
  # GET /noticias/1.json
  def show
  end

  # GET /noticias/new
  def new
    @noticia = Noticia.new
  end

  # GET /noticias/1/edit
  def edit
  end

  # POST /noticias
  # POST /noticias.json
  def create
    @noticia = Noticia.new(noticia_params)

    respond_to do |format|
      if @noticia.save
        format.html { redirect_to @noticia, notice: 'Noticia was successfully created.' }
        format.json { render :show, status: :created, location: @noticia }
      else
        format.html { render :new }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticias/1
  # PATCH/PUT /noticias/1.json
  def update
    respond_to do |format|
      if @noticia.update(noticia_params)
        format.html { redirect_to @noticia, notice: 'Noticia was successfully updated.' }
        format.json { render :show, status: :ok, location: @noticia }
      else
        format.html { render :edit }
        format.json { render json: @noticia.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticias/1
  # DELETE /noticias/1.json
  def destroy
    @noticia.destroy
    respond_to do |format|
      format.html { redirect_to noticias_url, notice: 'Noticia was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticia
      @noticia = Noticia.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def noticia_params
      params.require(:noticia).permit(:titulo, :contenido)
    end
end

app/controllers/planetas_controller.rb
class PlanetasController < ApplicationController
  before_action :set_planeta, only: [:show, :edit, :update, :destroy]

  # GET /planetas
  # GET /planetas.json
  def index
    @planetas = Planeta.all
  end

  # GET /planetas/1
  # GET /planetas/1.json
  def show
  end

  # GET /planetas/new
  def new
    @planeta = Planeta.new
  end

  # GET /planetas/1/edit
  def edit
  end

  # POST /planetas
  # POST /planetas.json
  def create
    @planeta = Planeta.new(planeta_params)

    respond_to do |format|
      if @planeta.save
        format.html { redirect_to @planeta, notice: 'Planeta creado correctamente.' }
        format.json { render :show, status: :created, location: @planeta }
      else
        format.html { render :new }
        format.json { render json: @planeta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /planetas/1
  # PATCH/PUT /planetas/1.json
  def update
    respond_to do |format|
      if @planeta.update(planeta_params)
        format.html { redirect_to @planeta, notice: 'Planeta actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @planeta }
      else
        format.html { render :edit }
        format.json { render json: @planeta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /planetas/1
  # DELETE /planetas/1.json
  def destroy
    @planeta.destroy
    respond_to do |format|
      format.html { redirect_to planetas_url, notice: 'Planeta eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_planeta
      @planeta = Planeta.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def planeta_params
      params.require(:planeta).permit(:nombre, :foto, :fecha_descubrimiento, :masa_en_tierras, :periodo_rotacion, :periodo_orbital, :gravedad, :posicion)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, raise: false
  def new
  end

  def create
    usuario = Usuario.find_by_username(params[:username])
    if usuario && usuario.authenticate(params[:password])
      session[:usuario_id] = usuario.id
      session[:usuario_rol] = usuario.rol
      flash[:notice] = "Inicio de sesión correcto"
      redirect_to root_url

    else
      flash.now[:warning] = "Nombre de usuario o contraseña incorrectos"
      render "new"
    end
  end

  def destroy
    session[:usuario_id] = nil
    session[:usuario_rol] = nil
    redirect_to root_url
    flash[:success] = "Sesión cerrada correctamente"
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario creado correctamente.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def usuario_params
      params.require(:usuario).permit(:username, :rol, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/noticias_helper.rb
module NoticiasHelper
end

app/helpers/planetas_helper.rb
module PlanetasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/home/index.html.erb
<div class="container-fluid text-center">
    <img class="img-fluid" src="images/logo_title.png" width="750" height="212.5" alt="logo">
</div>

<div class="container mt-3">
    <div class="row">
        <div class="col-md-4 d-flex align-items-stretch">
            <div class="card text-white bg-secondary mb-3">
                <div class="zoom-background">
                    <%= link_to planetas_path do %>
                      <%= image_tag("/images/planets.jpg", class: "card-img-top", alt: "Card image cap") %>
                    <% end %>
                </div>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-center">Planetas</h5>
                    <p class="card-text">
                        Un planeta es un objeto astronómico que orbita una estrella.
                    </p>
                    <%= link_to "Ver", planetas_path, class: 'mt-auto btn btn-dark' %>
                </div>
            </div>
        </div>
        <div class="col-md-4 d-flex align-items-stretch">
            <div class="card text-white bg-secondary mb-3">
                <div class="zoom-background">
                    <%= image_tag("/images/stars.jpg", class: "card-img-top", alt: "Card image cap") %>
                </div>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-center">Estrellas</h5>
                    <p class="card-text">
                        Las estrellas son esferoides luminosos de plasma que mantienen su forma gracias a su propia gravedad.
                    </p>
                    <a href="#" class="mt-auto btn btn-dark">Ver</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 d-flex align-items-stretch">
            <div class="card text-white bg-secondary mb-3">
                <div class="zoom-background">
                    <%= image_tag("/images/galaxy.jpg", class: "card-img-top", alt: "Card image cap") %>
                </div>
                <div class="card-body d-flex flex-column">
                    <h5 class="card-title text-center">Galaxias</h5>
                    <p class="card-text">
                        Una galaxia es un conjunto de estrellas, nubes de gas, planetas, polvo cósmico, materia oscura y energía.
                    </p>
                    <a href="#" class="mt-auto btn btn-dark">Ver</a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="text-justify">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras rutrum maximus mollis. Donec sit amet dui sit amet nisi scelerisque
        venenatis eget in sem. Sed bibendum suscipit risus, a consequat nunc elementum ut. Nullam ac luctus felis. Fusce non egestas ante, at
        tristique nunc. Mauris nunc risus, facilisis eu scelerisque in, aliquam id velit. Maecenas aliquet venenatis tristique. Curabitur ac
        viverra tellus. Maecenas tristique, nisi in vulputate faucibus, enim justo fermentum urna, sed porta augue justo non ante. Integer ut
        tellus quis tortor venenatis fermentum vel vel justo. Sed rhoncus purus sit amet vulputate sollicitudin. Nam tincidunt enim metus, quis
        hendrerit nunc rhoncus ac. Nunc libero lacus, lobortis vel purus vel, pulvinar vehicula leo. Integer at ante at lectus mattis mollis.
        Vivamus sit amet cursus ligula. Quisque arcu sapien, ornare eget metus id, mollis tincidunt turpis.</p>

        <p>Pellentesque semper, turpis sit amet vulputate vulputate, diam libero auctor risus, at porta turpis leo nec nunc. Morbi porta leo erat,
        vitae porta metus rutrum hendrerit. Phasellus in mauris tempus, egestas est ac, ultricies lacus. Integer eu libero sagittis, tempor libero ut,
        condimentum turpis. Cras sit amet mi at orci cursus ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis fermentum cursus
        fermentum.</p>

        <p>Mauris varius urna egestas pretium viverra. Etiam iaculis arcu justo, quis tristique dolor convallis nec. Etiam quam dui, pulvinar nec efficitur
        quis, feugiat sit amet ligula. Morbi quis libero commodo velit facilisis commodo. Maecenas vehicula convallis nulla eu viverra. Proin hendrerit
        justo in dui ullamcorper pellentesque. Aliquam iaculis, tortor sodales convallis vulputate, erat dolor laoreet lacus, ac condimentum ante augue
        id nibh. Morbi dictum, massa ut tempus interdum, urna magna venenatis enim, vitae blandit leo ipsum ut nulla. Nam non mi tristique, auctor arcu
        eu, ultrices metus. Suspendisse enim erat, maximus lacinia massa at, suscipit tempus massa. Vestibulum ante ipsum primis in faucibus orci luctus
        et ultrices posuere cubilia curae;</p>

        <p>Sed sodales tortor sed justo efficitur elementum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
        Suspendisse porta justo nisi, at malesuada odio tempor non. Morbi quis ante erat. Phasellus ultricies elit turpis, quis gravida ligula lacinia
        in. Ut vitae sollicitudin felis. Nullam at augue dui. Proin vel bibendum dui, nec tristique ipsum. Praesent in lorem tortor. Quisque malesuada
        sapien metus, ac semper ante tempor non.</p>

        <p>Maecenas vel libero luctus, aliquam arcu sit amet, tempor elit. Cras eu tortor a velit hendrerit gravida in vitae nulla. Nulla facilisi.
        Quisque et tristique eros, vel aliquam leo. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus placerat orci in congue hendrerit.
        Donec quis orci in ipsum congue dictum ut sit amet eros. Vestibulum congue dolor a enim pharetra, a consequat nisl dignissim. Nam laoreet urna sed
        luctus faucibus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Duis a lorem hendrerit, molestie urna ut, pretium urna.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ouroboros Space</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="<%= root_path %>">
          <%= image_tag("/images/logo.png", size: "100x100", alt: "logo") %>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item <%= 'active' if params[:controller] == 'home' %> %>">
                <%= link_to "Home", root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item  <%= 'active' if params[:controller] == 'noticias' %>">
                <%= link_to "Noticias", noticias_path, class: 'nav-link'%>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Planetas
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Mercurio</a>
                  <a class="dropdown-item" href="#">Venus</a>
                  <a class="dropdown-item" href="#">La Tierra</a>
                  <a class="dropdown-item" href="#">Marte</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="<%= planetas_path %>">Ver todos</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Estrellas
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Sol</a>
                  <a class="dropdown-item" href="#">Betelgeuse</a>
                  <a class="dropdown-item" href="#">Próxima Centauri</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Ver todas</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Galaxias
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="#">Vía Láctea</a>
                  <a class="dropdown-item" href="#">Andrómeda</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Ver todas</a>
                </div>
              </li>
          </ul>

          <form class="form-inline my-2 my-lg-0">
            <% if session[:usuario_rol] == 'Administrador' %>
              <div class="navbar-nav">
                <div class="nav-item">
                  <%= link_to "Usuarios", usuarios_path, class: 'nav-link'%>
                </div>
              </div>
            <% end %>

            <% if session[:usuario_id] == nil %>
              <a class="btn btn-outline-secondary mr-sm-2" href="/login" type="submit">Iniciar sesión</a>
            <% else %>
              <a class="btn btn-outline-secondary mr-sm-2" href="/logout" type="submit">Cerrar sesión</a>
            <% end %>
            <input class="form-control mr-sm-2" type="search" placeholder="🔍 Buscar..." aria-label="Search">
          </form>
      </div>
    </nav>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class="container-fluid text-center alert alert-info alert-dismissible fade show mt-2" role="alert">
        <strong><%= msg %></strong>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/noticias/_form.html.erb
<%= form_with(model: noticia, local: true) do |form| %>
  <% if noticia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(noticia.errors.count, "error") %> prohibited this noticia from being saved:</h2>

      <ul>
        <% noticia.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :titulo %>
    <%= form.text_field :titulo %>
  </div>

  <div class="field">
    <%= form.label :contenido %>
    <%= form.text_area :contenido %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/noticias/edit.html.erb
<h1>Editing Noticia</h1>

<%= render 'form', noticia: @noticia %>

<%= link_to 'Show', @noticia %> |
<%= link_to 'Back', noticias_path %>

app/views/noticias/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Noticias</h1>

  <% if session[:usuario_rol] == 'Administrador' %>
    <div class="table">
    <table>
      <thead>
        <tr>
          <th>Título</th>
          <th>Contenido</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @noticias.each do |noticia| %>
          <tr>
            <td><%= noticia.titulo.truncate(50) %></td>
            <td><%= noticia.contenido.truncate(50) %></td>
            <td><%= link_to 'Ver', noticia %></td>
            <td><%= link_to 'Editar', edit_noticia_path(noticia) %></td>
            <td><%= link_to 'Eliminar', noticia, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    <br>

    <%= link_to 'Nueva noticia', new_noticia_path %>

  <% else %>
    <% @noticias.each do |noticia| %>
      <div class="container">
        <div class="card mb-3">
          <div class="card-header">
            <%= noticia.titulo %>
          </div>
          <div class="card-body">
            <p class="card-text"><%= noticia.contenido.truncate(200, :separator => ' ') %></p>
            <%= link_to "Leer más", noticia, class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/noticias/new.html.erb
<h1>New Noticia</h1>

<%= render 'form', noticia: @noticia %>

<%= link_to 'Back', noticias_path %>

app/views/noticias/show.html.erb
<div class="container">
  <h1>
    <%= @noticia.titulo %>
  </h1>

  <p class="text-justify">
    <%= @noticia.contenido %>
  </p>
</div>

<% if session[:usuario_rol] == 'Administrador' %>
  <%= link_to 'Editar', edit_noticia_path(@noticia) %> |
  <%= link_to 'Atrás', noticias_path %>
<% end %>

app/views/planetas/edit.html.erb
<h1>Editing Planeta</h1>

<%= render 'form', planeta: @planeta %>

<%= link_to 'Show', @planeta %> |
<%= link_to 'Back', planetas_path %>

app/views/planetas/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Planetas</h1>

  <% if session[:usuario_rol] == 'Administrador' %>
    <div class="table">
      <table>
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Foto</th>
            <th>Fecha descubrimiento</th>
            <th>Masa en tierras</th>
            <th>Periodo rotación</th>
            <th>Periodo orbital</th>
            <th>Gravedad</th>
            <th>Posición</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @planetas.each do |planeta| %>
            <tr>
              <td><%= planeta.nombre %></td>
              <td><%= planeta.foto %></td>
              <td><%= planeta.fecha_descubrimiento %></td>
              <td><%= planeta.masa_en_tierras %></td>
              <td><%= planeta.periodo_rotacion %></td>
              <td><%= planeta.periodo_orbital %></td>
              <td><%= planeta.gravedad %></td>
              <td><%= planeta.posicion %></td>
              <td><%= link_to 'Ver', planeta %></td>
              <td><%= link_to 'Editar', edit_planeta_path(planeta) %></td>
              <td><%= link_to 'Eliminar', planeta, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <br>

    <%= link_to 'Nuevo planeta', new_planeta_path %>

  <% else %>
    <% planetas = Planeta.all.to_a %>
    <% planetas = planetas.sort_by(&:posicion) %>

    <% planetas.each do |planeta| %>
      <div class="container">
        <div class="card border-dark mb-3" >
          <div class="row no-gutters">
            <div class="col-md-4">
              <%= image_tag("/images/" + planeta.foto, class: "card-img", alt: "Card image cap") %>
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h2 class="card-title"><%= planeta.nombre %></h2>
                <strong>Fecha de descubrimiento:</strong>
                <p class="card-text"><%= planeta.fecha_descubrimiento %></p>
                <strong>Masa:</strong>
                <p class="card-text"><%= (Planeta.masa_de_la_tierra * planeta.masa_en_tierras).to_f %> kg (<%= planeta.masa_en_tierras.truncate(3) %> Tierras)</p>
                <strong>Periodo de rotación:</strong>
                <p class="card-text"><%= planeta.periodo_rotacion %></p>
                <strong>Periodo orbital:</strong>
                <p class="card-text"><%= planeta.periodo_orbital %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>


</div>

app/views/planetas/new.html.erb
<h1>New Planeta</h1>

<%= render 'form', planeta: @planeta %>

<%= link_to 'Back', planetas_path %>

app/views/planetas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @planeta.nombre %>
</p>

<p>
  <strong>Foto:</strong>
  <%= @planeta.foto %>
</p>

<p>
  <strong>Fecha descubrimiento:</strong>
  <%= @planeta.fecha_descubrimiento %>
</p>

<p>
  <strong>Masa en tierras:</strong>
  <%= @planeta.masa_en_tierras %>
</p>

<p>
  <strong>Periodo rotación:</strong>
  <%= @planeta.periodo_rotacion %>
</p>

<p>
  <strong>Periodo orbital:</strong>
  <%= @planeta.periodo_orbital %>
</p>

<p>
  <strong>Gravedad:</strong>
  <%= @planeta.gravedad %>
</p>

<p>
  <strong>Posición:</strong>
  <%= @planeta.posicion %>
</p>

<%= link_to 'Edit', edit_planeta_path(@planeta) %> |
<%= link_to 'Back', planetas_path %>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form">
    <div class="field form-group">
      <%= form.label 'Nombre de usuario' %>
      <%= form.text_field :username %>
    </div>

    <div class="field form-group">
      <%= form.label 'Rol' %>
      <%= form.select :rol, options_for_select(['Administrador', 'Editor']) %>
    </div>

    <div class="field form-group">
      <%= form.label 'Contraseña' %>
      <%= form.password_field :password %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Ver', @usuario %> |
<%= link_to 'Volver', usuarios_path %>

app/views/usuarios/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Usuarios</h1>

  <div class="table">
    <table>
      <thead>
        <tr>
          <th>Nombre de usuario</th>
          <th>Rol</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @usuarios.each do |usuario| %>
          <tr>
            <td><%= usuario.username %></td>
            <td><%= usuario.rol %></td>
            <td><%= link_to 'Ver', usuario %></td>
            <td><%= link_to 'Editar', edit_usuario_path(usuario) %></td>
            <td><%= link_to 'Eliminar', usuario, method: :delete,
              data: { confirm: '¿Estás seguro?' } %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to 'Nuevo usuario', new_usuario_path %>
</div>

app/views/usuarios/new.html.erb
<div class="container">
  <h1>New Usuario</h1>

  <%= render 'form', usuario: @usuario %>

  <%= link_to 'Atrás', usuarios_path %>
</div>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre de usuario:</strong>
  <%= @usuario.username %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @usuario.rol %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>